all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    caddy_domain: your-domain.example.com
    caddy_email: you@example.com
    caddy_backend_port: 8080
    ollama_host: 0.0.0.0
    ollama_port: 11434
    ollama_api_url: http://127.0.0.1:11434
    frontend_api_url: https://ollama.your-domain.example.com
    ollama_model: gemma4:e4b
  children:
    webservers:
      hosts:
        hetzner-vps:
          ansible_host: 203.0.113.10
