all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    caddy_domain: ai-operator.kcrl-devops.de
    caddy_email: kamgoche@yahoo.com
    caddy_backend_port: 8080
  children:
    webservers:
      hosts:
        app01:
          # ansible_host: 192.168.1.10
          ansible_host: ai-operator.kcrl-devops.de
