---
- name: Restart systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
  listen: restart time sync

- name: Restart Caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
  listen: Restart Caddy
